### ISSUE TITLE
After add new issue into related issues list ("#relations") added issue doesn't show

### ISSUE THREAD

**Issue by TrumanRu** [kenan3008/redmine_issue_view_columns#4]
1. Open any issue.
2. Push "Add" link at "Related issues" section.
 ( => form "" opened)
3. Input any issue number.
4. Push "Add" form button.
 ( => progress indicator for about 2 seconds then... nothing)

Uninstalling plugin resolve the problem.

**Comment by TrumanRu** [comment]
```Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.7-p456 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.10.2
  Git                            2.19.1
  Filesystem                     
  GitMirror                      2.19.1
Redmine plugins:
  a_common_libs                  2.5.3
  custom_menu                    1.8.5
  easy_gantt                     1.12
  easy_mindmup                   1.0
  easy_wbs                       1.5
  extra_queries                  2.3.5
  global_roles                   2.2.4
  issue_id                       0.0.2
  redmine_attribute_quickies     1.0.2
  redmine_base_deface            1.3.2
  redmine_better_overview        1.0.0
  redmine_checklists             3.1.11
  redmine_custom_workflows       0.1.6
  redmine_default_custom_query   1.3.0
  redmine_edit_custom_fields     0.0.5
  redmine_gemavatar              1.1
  redmine_git_mirror             0.8.0
  redmine_inline_auto_complete   0.1.0
  redmine_issue_tabs             1.3.2
  redmine_issue_view_columns     1.0.1
  redmine_merge_request_links    2.1.1
  redmine_more_code              1.0.0
  redmine_more_context           1.0.0
  redmine_my_page                0.1.13
  redmine_workflow_enhancements  0.5.0
  redmine_wysiwyg_editor         0.5.0
  redmine_xlsx_format_issue_exporter 0.1.6
  scrum                          0.18.0
  that_email_log                 0.0.2
  unread_issues                  2.2.3
  usability                      2.3.9
  view_customize                 2.1.0
  westaco_versions               0.0.2```

**Comment by poxtihc** [comment]
Here the log:

Completed 500 Internal Server Error in 266ms (ActiveRecord: 46.4ms)

ActionView::Template::Error (undefined method `column_content' for #<#<Class:0x000055c4ec37bed0>:0x00007efc91308718>):
     8:
     9: <% if @relations.present? %>
    10: <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
    11:   <%= render_issue_relations(@issue, @relations) %>
    12: <% end %>
    13: <% end %>
    14:

plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:91:in `block (2 levels) in render_issue_relations'
plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:89:in `each'
plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:89:in `block in render_issue_relations'
plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:74:in `each'
plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:74:in `render_issue_relations'

**Comment by speedy32129** [comment]
Found the same issue with version 1.0.0.

> Environment:
  Redmine version                4.0.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  5.2.2.1
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                sendmail
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  projects_tree_view             0.0.9
  redmine_issue_view_columns     1.0.0
  redmine_knowledgebase          4.0.0
  redmine_scm_path_view          0.0.2
  time_logger                    0.5.4
